/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LagRouteImport } from './routes/lag'
import { Route as OmRouteImport } from './routes/om'
import { Route as DebuggServerklockaRouteImport } from './routes/debugg.serverklocka'
import { Route as LagTeamIdRouteImport } from './routes/lag_.$teamId'
import { Route as MatchesMatchIdSummaryRouteImport } from './routes/matches_.$matchId.summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LagRoute = LagRouteImport.update({
  id: '/lag',
  path: '/lag',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const DebuggServerklockaRoute = DebuggServerklockaRouteImport.update({
  id: '/debugg/serverklocka',
  path: '/debugg/serverklocka',
  getParentRoute: () => rootRouteImport,
} as any)
const LagTeamIdRoute = LagTeamIdRouteImport.update({
  id: '/lag_/$teamId',
  path: '/lag/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdSummaryRoute = MatchesMatchIdSummaryRouteImport.update({
  id: '/matches_/$matchId/summary',
  path: '/matches/$matchId/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lag': typeof LagRoute
  '/om': typeof OmRoute
  '/debugg/serverklocka': typeof DebuggServerklockaRoute
  '/lag/$teamId': typeof LagTeamIdRoute
  '/matches/$matchId/summary': typeof MatchesMatchIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lag': typeof LagRoute
  '/om': typeof OmRoute
  '/debugg/serverklocka': typeof DebuggServerklockaRoute
  '/lag/$teamId': typeof LagTeamIdRoute
  '/matches/$matchId/summary': typeof MatchesMatchIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lag': typeof LagRoute
  '/om': typeof OmRoute
  '/debugg/serverklocka': typeof DebuggServerklockaRoute
  '/lag_/$teamId': typeof LagTeamIdRoute
  '/matches_/$matchId/summary': typeof MatchesMatchIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lag'
    | '/om'
    | '/debugg/serverklocka'
    | '/lag/$teamId'
    | '/matches/$matchId/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lag'
    | '/om'
    | '/debugg/serverklocka'
    | '/lag/$teamId'
    | '/matches/$matchId/summary'
  id:
    | '__root__'
    | '/'
    | '/lag'
    | '/om'
    | '/debugg/serverklocka'
    | '/lag_/$teamId'
    | '/matches_/$matchId/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LagRoute: typeof LagRoute
  OmRoute: typeof OmRoute
  DebuggServerklockaRoute: typeof DebuggServerklockaRoute
  LagTeamIdRoute: typeof LagTeamIdRoute
  MatchesMatchIdSummaryRoute: typeof MatchesMatchIdSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lag': {
      id: '/lag'
      path: '/lag'
      fullPath: '/lag'
      preLoaderRoute: typeof LagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debugg/serverklocka': {
      id: '/debugg/serverklocka'
      path: '/debugg/serverklocka'
      fullPath: '/debugg/serverklocka'
      preLoaderRoute: typeof DebuggServerklockaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lag_/$teamId': {
      id: '/lag_/$teamId'
      path: '/lag/$teamId'
      fullPath: '/lag/$teamId'
      preLoaderRoute: typeof LagTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches_/$matchId/summary': {
      id: '/matches_/$matchId/summary'
      path: '/matches/$matchId/summary'
      fullPath: '/matches/$matchId/summary'
      preLoaderRoute: typeof MatchesMatchIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LagRoute: LagRoute,
  OmRoute: OmRoute,
  DebuggServerklockaRoute: DebuggServerklockaRoute,
  LagTeamIdRoute: LagTeamIdRoute,
  MatchesMatchIdSummaryRoute: MatchesMatchIdSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
