/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OmRouteImport } from './routes/om'
import { Route as DebuggServerklockaRouteImport } from './routes/debugg.serverklocka'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const DebuggServerklockaRoute = DebuggServerklockaRouteImport.update({
  id: '/debugg/serverklocka',
  path: '/debugg/serverklocka',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/om': typeof OmRoute
  '/debugg/serverklocka': typeof DebuggServerklockaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/om': typeof OmRoute
  '/debugg/serverklocka': typeof DebuggServerklockaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/om': typeof OmRoute
  '/debugg/serverklocka': typeof DebuggServerklockaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/om' | '/debugg/serverklocka'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/om' | '/debugg/serverklocka'
  id: '__root__' | '/' | '/om' | '/debugg/serverklocka'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OmRoute: typeof OmRoute
  DebuggServerklockaRoute: typeof DebuggServerklockaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debugg/serverklocka': {
      id: '/debugg/serverklocka'
      path: '/debugg/serverklocka'
      fullPath: '/debugg/serverklocka'
      preLoaderRoute: typeof DebuggServerklockaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OmRoute: OmRoute,
  DebuggServerklockaRoute: DebuggServerklockaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
